import Layout from '../components/layout'
import '../styles/globals.scss'
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
          <Head>
        <title>Techonomic</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
        {/* <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap'
          rel='stylesheet'
        /> */}
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp
